export const SET_ASREVIEW_VERSION = "SET_ASREVIEW_VERSION";

export const SET_PROJECT = "SET_PROJECT";
export const SET_APP_STATE = "SET_APP_STATE";
export const TOGGLE_REVIEW_DRAWER = "TOGGLE_REVIEW_DRAWER";
