# First stage
FROM python:3.8-slim AS builder
WORKDIR /app

# Copy and build asreview
# git is used by versioneer to define the project version
COPY . /app
RUN rm -rf /app/asreview/webapp/build
RUN rm -rf /app/asreview/webapp/node_modules
RUN rm -rf /app/asreview/webapp/public
RUN rm -rf /app/asreview/webapp/src

RUN apt-get update \
    && apt-get install -y git build-essential\
    && pip3 install --upgrade pip setuptools \
    && pip3 install --user gunicorn \
    && pip3 install --user . \
    && pip3 install --user asreview-datatools asreview-insights asreview-makita asreview-wordcloud

# Second stage
FROM python:3.8-slim

RUN apt-get update && apt-get install -y curl && apt-get install -y procps

WORKDIR /app
COPY --from=builder /root/.local /root/.local

# copy config file to Image
COPY ./Docker/auth_verified/flask_config.toml ${WORKDIR}

ENV PATH=/root/.local/bin:$PATH
ENV ASREVIEW_PATH=/app/project_folder
ENV FLASK_CONFIGFILE=/app/flask_config.toml

WORKDIR /root/.local/lib/python3.8/site-packages/asreview/webapp
COPY ./Docker/auth_verified/wsgi.py ${WORKDIR}

ENTRYPOINT ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:5013", "wsgi:app"]