DEBUG = true
HOST = "0.0.0.0"
PORT = 5000
AUTHENTICATION_ENABLED = true
ALLOWED_ORIGINS = ["http://localhost:8080", "http://127.0.0.1:8080"]
SECRET_KEY = "my_very_secret_key"
SECURITY_PASSWORD_SALT = "abCDefGH"
SESSION_COOKIE_SECURE = true
REMEMBER_COOKIE_SECURE = true
SESSION_COOKIE_SAMESITE = "Lax"
SQLALCHEMY_TRACK_MODIFICATIONS = true
ALLOW_ACCOUNT_CREATION = true
ALLOW_TEAMS = false
EMAIL_VERIFICATION = true
SQLALCHEMY_DATABASE_URI = "postgresql+psycopg2://asreview:asreview@asreview_database:5432/asreview"

[EMAIL_CONFIG]
SERVER = "smtp.sendgrid.net"
PORT = 465
USERNAME = "apikey"
PASSWORD = "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"
USE_TLS = false
USE_SSL = true
REPLY_ADDRESS = "casper@compunist.nl"
